In [1]:
import numpy as np
import scipy

In [2]:
def SOS(A):
    x=0
    for i in A:
        x+=i**2
    return x

In [3]:
def eprod(A,B):
    L=[]
    for i in range(len(A)):
        L.append(A[i]*B[i])
    return(L)

In [4]:
#y=b1*x1+b2*x2

In [5]:
X=np.transpose([[300,305,310,315],
            [525,520,510,500]])
Y=np.array([218,215,216,212])
n=np.shape(X)[0]
p=2                                       #edit manually

In [6]:
b=np.matmul(np.transpose(X),X)
b=np.matmul(np.linalg.inv(b),np.transpose(X))
b=np.matmul(b,Y)

In [7]:
b

array([0.18839198, 0.30621639])

In [8]:
y_hat=np.matmul(X,b)

In [9]:
y_hat

array([217.28119944, 216.69207737, 214.57187334, 212.45166932])

In [10]:
SR=SOS(Y-y_hat)
SR

5.6233509952477405

In [11]:
s2_exp=SR/(n-p)
s2_exp

2.8116754976238703

In [12]:
rho=-sum(eprod(X[:,0],X[:,1]))/(np.sqrt(SOS(X[:,0]))*np.sqrt(SOS(X[:,1])))
rho

-0.9993240656445055

In [13]:
corr_mat=np.array([[1,rho],[rho,1]])
corr_mat

array([[ 1.        , -0.99932407],
       [-0.99932407,  1.        ]])

In [14]:
V_b1=s2_exp/((1-rho**2)*SOS(X[:,0]))
SD_b1=np.sqrt(V_b1)
print("V(b1)= {}".format(V_b1))
print("SD(b1)= {}".format(SD_b1))
print("t-ratio for b1= {}".format(b[0]/SD_b1))
LOS_b1=1-scipy.stats.t.cdf(b[0]/SD_b1, (n-p))
print("LOS for b1= {}".format(2*LOS_b1))

V(b1)= 0.005499000303104457
SD(b1)= 0.07415524460956525
t-ratio for b1= 2.5405078191183548
LOS for b1= 0.12625482334616067


In [15]:
V_b2=s2_exp/((1-rho**2)*SOS(X[:,1]))
SD_b2=np.sqrt(V_b2)
print("V(b2)= {}".format(V_b2))
print("SD(b2)= {}".format(SD_b2))
print("t-ratio for b2= {}".format(b[1]/SD_b2))
LOS_b2=1-scipy.stats.t.cdf(b[1]/SD_b2, (n-p))
print("LOS for b2= {}".format(2*LOS_b2))

V(b2)= 0.0019699815501759465
SD(b2)= 0.04438447420186417
t-ratio for b2= 6.899178091490448
LOS for b2= 0.020369289673785262


In [16]:
SM=SOS(y_hat)
print("Model: DOF= {} SM= {} SM2= {}".format(p,SM,SM/p))
print("Error: DOF= {} SR= {} SR2= {}".format(n-p,SR,SR/(n-p)))
print("Total: DOF= {} ST= {}".format(n,SM+SR))
print("F-ratio: {}".format((SM/p)/(SR/(n-p))))

Model: DOF= 2 SM= 185343.37664893852 SM2= 92671.68832446926
Error: DOF= 2 SR= 5.6233509952477405 SR2= 2.8116754976238703
Total: DOF= 4 ST= 185348.99999993376
F-ratio: 32959.595942983295
